### ISSUE TITLE
Error - standard use case

### ISSUE THREAD

**Issue by Lhdang88** [StayFN/URL-Shortener#1]
<img width="1440" alt="Screenshot 2020-07-27 at 15 29 05" src="https://user-images.githubusercontent.com/13630800/88547663-557be280-d01e-11ea-9f74-2e7851d41e11.png">

<img width="1434" alt="Screenshot 2020-07-27 at 15 30 33" src="https://user-images.githubusercontent.com/13630800/88547736-688eb280-d01e-11ea-9220-bb30c7143a72.png">

<img width="1440" alt="Screenshot 2020-07-27 at 15 30 51" src="https://user-images.githubusercontent.com/13630800/88547561-38dfaa80-d01e-11ea-8c24-f407f678ea85.png">

**Comment by StayFN** [comment]
Konnte ich reproduzieren, hatte anscheinend irgendwann ausversehen den Aufruf des Tokengenerators rausgenommen, sodass die Kurzurl wenn nix eingetragen war immer null war. Müsste jetzt klappen, sorry.
