### ISSUE TITLE
Redirection- Failed to redirect

### ISSUE THREAD

**Issue by Lhdang88** [StayFN/URL-Shortener#2]
instead to redirect, the server redirects to: localhost:8080/URL

**Comment by Stungler** [comment]
When exactly does this happen? Can't reproduce it.

**Comment by Stungler** [comment]
https://www.youtube.com/watch?v=rpSsF9HMZBE&feature=youtu.be

Do you experience other behaviour as demonstrated in the video?

**Comment by Lhdang88** [comment]
It's fixed now. OK.
