### ISSUE TITLE
Failed to detect collisions / existing short-URLs

### ISSUE THREAD

**Issue by Lhdang88** [StayFN/URL-Shortener#3]
1. First URL is shortened to localhost:8080/yt
2. Second URL is also shortened to localhost:8080/yt -> the first Short-URL becomes overwritten -> this is an error (and also a security issue)

**Comment by Stungler** [comment]
Added collision detection. Hope it now works as intended.

![grafik](https://user-images.githubusercontent.com/47352800/88592185-df976b80-d05d-11ea-822b-cb2de9d3c5f3.png)
